/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.*;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkIJTheme;
import java.awt.geom.Arc2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Ezequiel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/recursos/universidad.png"));
        Image miImagen=icono.getImage();
        fondo = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jMIFormAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        JMIFormMateria = new javax.swing.JMenuItem();
        Administracion = new javax.swing.JMenu();
        jMIManDeInscripciones = new javax.swing.JMenuItem();
        jMIManDeNotas = new javax.swing.JMenuItem();
        JMConsultas = new javax.swing.JMenu();
        jMIAlumnoPorMateria = new javax.swing.JMenuItem();
        JMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1142, 643));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jMAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/alumno.png"))); // NOI18N

        jMIFormAlumno.setText("Formulario de alumno");
        jMIFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormAlumnoActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMIFormAlumno);

        jMenuBar1.add(jMAlumnos);

        jMMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/materia.png"))); // NOI18N

        JMIFormMateria.setText("Formulario de materia");
        JMIFormMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIFormMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(JMIFormMateria);

        jMenuBar1.add(jMMateria);

        Administracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/administracion.png"))); // NOI18N

        jMIManDeInscripciones.setText("Manejo de inscripciones");
        jMIManDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManDeInscripcionesActionPerformed(evt);
            }
        });
        Administracion.add(jMIManDeInscripciones);

        jMIManDeNotas.setText("Manipulación de notas");
        jMIManDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManDeNotasActionPerformed(evt);
            }
        });
        Administracion.add(jMIManDeNotas);

        jMenuBar1.add(Administracion);

        JMConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/consulta.png"))); // NOI18N
        JMConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConsultasActionPerformed(evt);
            }
        });

        jMIAlumnoPorMateria.setText("Alumnos por materia");
        JMConsultas.add(jMIAlumnoPorMateria);

        jMenuBar1.add(JMConsultas);

        JMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salir.png"))); // NOI18N
        JMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormAlumnoActionPerformed
        fondo.removeAll();
        fondo.repaint();
        VistaAlumno va  = new VistaAlumno();
        va.setVisible(true);
        fondo.add(va);
        fondo.moveToFront(va);        // TODO add your handling code here:
    }//GEN-LAST:event_jMIFormAlumnoActionPerformed

    private void JMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JMSalirMouseClicked

    private void JMIFormMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIFormMateriaActionPerformed
        fondo.removeAll();
        fondo.repaint();
        VistaMateria vm = new VistaMateria();
        vm.setVisible(true);
        fondo.add(vm);
        fondo.moveToFront(vm);
    }//GEN-LAST:event_JMIFormMateriaActionPerformed

    private void jMIManDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManDeInscripcionesActionPerformed
        // TODO add your handling code here:
        fondo.removeAll();
        fondo.repaint();
        VistaInscripcion vi = new VistaInscripcion();
        vi.setVisible(true);
        fondo.add(vi);
        fondo.moveToFront(vi);
    }//GEN-LAST:event_jMIManDeInscripcionesActionPerformed

    private void jMIManDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManDeNotasActionPerformed
        fondo.removeAll();
        fondo.repaint();
        VistaNotas vn = new VistaNotas();
        vn.setVisible(true);
        fondo.add(vn);
        fondo.moveToFront(vn);
    }//GEN-LAST:event_jMIManDeNotasActionPerformed

    private void JMConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatGitHubDarkIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
            System.out.println("Error al establecer el tema");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administracion;
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JMenuItem JMIFormMateria;
    private javax.swing.JMenu JMSalir;
    private javax.swing.JDesktopPane fondo;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenuItem jMIAlumnoPorMateria;
    private javax.swing.JMenuItem jMIFormAlumno;
    private javax.swing.JMenuItem jMIManDeInscripciones;
    private javax.swing.JMenuItem jMIManDeNotas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
