
package vistas;

import Entidades.Alumno;
import EntidadesData.AlumnoData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 3
 */
public class AlumnosVista extends javax.swing.JInternalFrame {
    private Alumno aluActual = null;
    AlumnoData alu = new AlumnoData();
    
    /**
     * Creates new form Alumnos
     */
    public AlumnosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTFDocAlum = new javax.swing.JTextField();
        jTFNomAlum = new javax.swing.JTextField();
        jTFApellidoAlum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBBuscarAlum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBEliminarAlum = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBNuevoAlum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBGuardarAlum = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBSalirAlum = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRBEstadoAlum = new javax.swing.JRadioButton();
        jDateCFecha = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alumno");

        jBBuscarAlum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBBuscarAlum.setText("Buscar");
        jBBuscarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarAlumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jBEliminarAlum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBEliminarAlum.setText("Eliminar");
        jBEliminarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarAlumActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        jBNuevoAlum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBNuevoAlum.setText("Nuevo");
        jBNuevoAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoAlumActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Documento:");

        jBGuardarAlum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBGuardarAlum.setText("Guardar");
        jBGuardarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarAlumActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Estado:");

        jBSalirAlum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBSalirAlum.setText("Salir");
        jBSalirAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirAlumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Fecha de nacimiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBNuevoAlum)
                .addGap(18, 18, 18)
                .addComponent(jBEliminarAlum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBGuardarAlum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSalirAlum)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBEstadoAlum)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTFNomAlum)
                                            .addComponent(jTFApellidoAlum)
                                            .addComponent(jTFDocAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(jBBuscarAlum))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33)
                                .addComponent(jDateCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTFDocAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBBuscarAlum))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFNomAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28))
                        .addComponent(jTFApellidoAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRBEstadoAlum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalirAlum)
                    .addComponent(jBEliminarAlum)
                    .addComponent(jBNuevoAlum)
                    .addComponent(jBGuardarAlum))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarAlumActionPerformed
       try{
           Integer dni = Integer.parseInt(jTFDocAlum.getText());
           aluActual = alu.buscarAlumnoPorDni(dni);
           if (aluActual!=null){
               jTFNomAlum.setText(aluActual.getNombre());
               jTFApellidoAlum.setText(aluActual.getApellido());
               jRBEstadoAlum.setSelected(aluActual.isEstado());
               LocalDate fn = aluActual.getFechaNacimiento();
               java.util.Date d = java.util.Date.from(fn.atStartOfDay(ZoneId.systemDefault()).toInstant());
               jDateCFecha.setDate(d);
           }
       } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El DNI debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jBBuscarAlumActionPerformed

    private void jBGuardarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarAlumActionPerformed
       try{
        Integer dni = Integer.parseInt(jTFDocAlum.getText());
        String nom = jTFNomAlum.getText().trim();
        String ap = jTFApellidoAlum.getText().trim();
        if (nom.isEmpty() || ap.isEmpty()){
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
           return;
        }
        boolean estado = jRBEstadoAlum.isSelected();
        Date fecha = jDateCFecha.getDate();
        LocalDate lD = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (aluActual == null) {
                aluActual = new Alumno(dni, nom, ap, lD, estado);
                alu.guardarAlumno(aluActual);
            } else {
                aluActual.setDni(dni);
                aluActual.setNombre(nom);
                aluActual.setApellido(ap);
                aluActual.setFechaNacimiento(lD);
                alu.modificarAlumno(aluActual);
            }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El DNI debe ser un número valido", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jBGuardarAlumActionPerformed

    private void jBSalirAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirAlumActionPerformed
         dispose();
    }//GEN-LAST:event_jBSalirAlumActionPerformed

    private void jBNuevoAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoAlumActionPerformed
        jTFDocAlum.setText("");
        jTFNomAlum.setText("");
        jTFApellidoAlum.setText("");
        jRBEstadoAlum.setSelected(true);
        jDateCFecha.setDate(new Date());
        aluActual = null;
    }//GEN-LAST:event_jBNuevoAlumActionPerformed

    private void jBEliminarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarAlumActionPerformed
       if (aluActual!=null){
           alu.eliminarAlumno(aluActual.getIdAlumno());
           aluActual = null;
           jTFDocAlum.setText("");
           jTFNomAlum.setText("");
           jTFApellidoAlum.setText("");
           jRBEstadoAlum.setSelected(true);
           jDateCFecha.setDate(new Date());
       } else {
           JOptionPane.showMessageDialog(this, "No se busco un alumno a eliminar");
       }
    }//GEN-LAST:event_jBEliminarAlumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarAlum;
    private javax.swing.JButton jBEliminarAlum;
    private javax.swing.JButton jBGuardarAlum;
    private javax.swing.JButton jBNuevoAlum;
    private javax.swing.JButton jBSalirAlum;
    private com.toedter.calendar.JDateChooser jDateCFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRBEstadoAlum;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFApellidoAlum;
    private javax.swing.JTextField jTFDocAlum;
    private javax.swing.JTextField jTFNomAlum;
    // End of variables declaration//GEN-END:variables
}
