
package vistas;

import Entidades.Materia;
import EntidadesData.MateriaData;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 3
 */
public class MateriasVista extends javax.swing.JInternalFrame {
    MateriaData materia = new MateriaData();
    private Materia mActual = null;
    
    /**
     * Creates new form Materias
     */
    public MateriasVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBGuardarMateria = new javax.swing.JButton();
        jTFCuatri = new javax.swing.JTextField();
        jBSalirMateria = new javax.swing.JButton();
        jBEliminarMateria = new javax.swing.JButton();
        jTFNomMateria = new javax.swing.JTextField();
        jBNuevoMateria = new javax.swing.JButton();
        jTFCodMateria = new javax.swing.JTextField();
        jRBEstadoMateria = new javax.swing.JRadioButton();
        jBBuscarMateria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Materia");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Estado:");

        jBGuardarMateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBGuardarMateria.setText("Guardar");
        jBGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarMateriaActionPerformed(evt);
            }
        });

        jBSalirMateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBSalirMateria.setText("Salir");
        jBSalirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirMateriaActionPerformed(evt);
            }
        });

        jBEliminarMateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBEliminarMateria.setText("Eliminar");
        jBEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarMateriaActionPerformed(evt);
            }
        });

        jBNuevoMateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBNuevoMateria.setText("Nuevo");
        jBNuevoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoMateriaActionPerformed(evt);
            }
        });

        jBBuscarMateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBBuscarMateria.setText("Buscar");
        jBBuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarMateriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Cuatrimestre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBNuevoMateria))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBEliminarMateria)
                                .addGap(28, 28, 28)
                                .addComponent(jBGuardarMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalirMateria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBEstadoMateria)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNomMateria)
                                    .addComponent(jTFCuatri)
                                    .addComponent(jTFCodMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jBBuscarMateria)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTFCodMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBBuscarMateria))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFNomMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28))
                        .addComponent(jTFCuatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRBEstadoMateria))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalirMateria)
                    .addComponent(jBEliminarMateria)
                    .addComponent(jBNuevoMateria)
                    .addComponent(jBGuardarMateria))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarMateriaActionPerformed
        try{
            Integer id = Integer.parseInt(jTFCodMateria.getText());
            mActual = materia.buscarMateria(id);
            if (mActual!=null){
              jTFNomMateria.setText(mActual.getNombre());
              String m = String.valueOf( mActual.getIdMateria());
              jTFCodMateria.setText(m);
              jTFCuatri.setText(mActual.getCuatrimestre());
              jRBEstadoMateria.setSelected(mActual.isEstado()); 
            }
        }catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El codigo debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBBuscarMateriaActionPerformed

    private void jBSalirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirMateriaActionPerformed
         dispose();
    }//GEN-LAST:event_jBSalirMateriaActionPerformed

    private void jBNuevoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoMateriaActionPerformed
        jTFCodMateria.setText("");
        jTFNomMateria.setText("");
        jTFCuatri.setText("");
        jRBEstadoMateria.setSelected(true);
        mActual = null;
    }//GEN-LAST:event_jBNuevoMateriaActionPerformed

    private void jBGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarMateriaActionPerformed
        try{
            Integer cod = Integer.parseInt(jTFCodMateria.getText());
            String nom = jTFNomMateria.getText().trim();
            String cua = jTFCuatri.getText().trim();
            if (nom.isEmpty() || cua.isEmpty()){
                JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
            return;}
            boolean e = jRBEstadoMateria.isSelected();
            if (mActual == null){
                mActual = new Materia(nom,cua,e);
                materia.guardarMateria(mActual);
            } else {
                mActual.setIdMateria(cod);
                mActual.setNombre(nom);
                mActual.setCuatrimestre(cua);
                mActual.setEstado(e);
                materia.modificarMateria(mActual);
            }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El codigo debe ser un número valido", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jBGuardarMateriaActionPerformed

    private void jBEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarMateriaActionPerformed
        if (mActual != null){
            materia.eliminarMateria(mActual.getIdMateria());
            mActual = null;
            jTFCodMateria.setText("");
            jTFNomMateria.setText("");
            jTFCuatri.setText("");
            jRBEstadoMateria.setSelected(true);
        } else {
           JOptionPane.showMessageDialog(this, "No se busco una materia a eliminar");
       }
    }//GEN-LAST:event_jBEliminarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarMateria;
    private javax.swing.JButton jBEliminarMateria;
    private javax.swing.JButton jBGuardarMateria;
    private javax.swing.JButton jBNuevoMateria;
    private javax.swing.JButton jBSalirMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRBEstadoMateria;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCodMateria;
    private javax.swing.JTextField jTFCuatri;
    private javax.swing.JTextField jTFNomMateria;
    // End of variables declaration//GEN-END:variables
}
