
package vistas;

import com.formdev.flatlaf.*;
import com.formdev.flatlaf.intellijthemes.*;


/**
 *
 * @author Grupo 3
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDPMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMIAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMIMateria = new javax.swing.JMenuItem();
        jMaAdmi = new javax.swing.JMenu();
        jMIInscri = new javax.swing.JMenuItem();
        jMINotas = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenu();
        jMIConsuXmateria = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDPMenuLayout = new javax.swing.GroupLayout(jDPMenu);
        jDPMenu.setLayout(jDPMenuLayout);
        jDPMenuLayout.setHorizontalGroup(
            jDPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jDPMenuLayout.setVerticalGroup(
            jDPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");

        jMIAlumno.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMIAlumno.setText("Formulario de Alumnos");
        jMIAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIAlumno);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        jMIMateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMIMateria.setText("Fomulario de materias");
        jMIMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMIMateria);

        jMenuBar1.add(jMMateria);

        jMaAdmi.setText("Administracion");

        jMIInscri.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMIInscri.setText("Manejo de inscripciones");
        jMIInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInscriActionPerformed(evt);
            }
        });
        jMaAdmi.add(jMIInscri);

        jMINotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMINotas.setText("Manipulacion de notas");
        jMINotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINotasActionPerformed(evt);
            }
        });
        jMaAdmi.add(jMINotas);

        jMenuBar1.add(jMaAdmi);

        jMConsulta.setText("Consulta");

        jMIConsuXmateria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMIConsuXmateria.setText("Alumnos por materias");
        jMIConsuXmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsuXmateriaActionPerformed(evt);
            }
        });
        jMConsulta.add(jMIConsuXmateria);

        jMenuBar1.add(jMConsulta);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumnoActionPerformed
        jDPMenu.removeAll();
        jDPMenu.repaint();
        AlumnosVista alum = new AlumnosVista();
        alum.setVisible(true);
        jDPMenu.add(alum);
        jDPMenu.moveToFront(alum);
    }//GEN-LAST:event_jMIAlumnoActionPerformed

    private void jMIMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMateriaActionPerformed
        jDPMenu.removeAll();
        jDPMenu.repaint();
        MateriasVista a = new MateriasVista();
        a.setVisible(true);
        jDPMenu.add(a);
        jDPMenu.moveToFront(a);
    }//GEN-LAST:event_jMIMateriaActionPerformed

    private void jMIInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInscriActionPerformed
        jDPMenu.removeAll();
        jDPMenu.repaint();
        formularioInscripcion m = new formularioInscripcion();
        m.setVisible(true);
        jDPMenu.add(m);
        jDPMenu.moveToFront(m);
    }//GEN-LAST:event_jMIInscriActionPerformed

    private void jMINotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINotasActionPerformed
       jDPMenu.removeAll();
        jDPMenu.repaint();
        cargaNota n = new cargaNota();
        n.setVisible(true);
        jDPMenu.add(n);
        jDPMenu.moveToFront(n);
    }//GEN-LAST:event_jMINotasActionPerformed

    private void jMIConsuXmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsuXmateriaActionPerformed
        jDPMenu.removeAll();
        jDPMenu.repaint();
        AlumnosXMateria n = new AlumnosXMateria();
        n.setVisible(true);
        jDPMenu.add(n);
        jDPMenu.moveToFront(n);
    }//GEN-LAST:event_jMIConsuXmateriaActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
        FlatVuesionIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
    });
        FlatGradiantoMidnightBlueIJTheme.setup();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPMenu;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsulta;
    private javax.swing.JMenuItem jMIAlumno;
    private javax.swing.JMenuItem jMIConsuXmateria;
    private javax.swing.JMenuItem jMIInscri;
    private javax.swing.JMenuItem jMIMateria;
    private javax.swing.JMenuItem jMINotas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenu jMaAdmi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
